// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kszafran/junction-2018/models"
)

// GetModuleInfoByIDReader is a Reader for the GetModuleInfoByID structure.
type GetModuleInfoByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModuleInfoByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetModuleInfoByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetModuleInfoByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 206:
		result := NewGetModuleInfoByIDPartialContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetModuleInfoByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetModuleInfoByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetModuleInfoByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetModuleInfoByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetModuleInfoByIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewGetModuleInfoByIDUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetModuleInfoByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 501:
		result := NewGetModuleInfoByIDNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewGetModuleInfoByIDServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 504:
		result := NewGetModuleInfoByIDGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetModuleInfoByIDOK creates a GetModuleInfoByIDOK with default headers values
func NewGetModuleInfoByIDOK() *GetModuleInfoByIDOK {
	return &GetModuleInfoByIDOK{}
}

/*GetModuleInfoByIDOK handles this case with default header values.

The request was successful. The result is contained in the response body.
*/
type GetModuleInfoByIDOK struct {
	Payload *models.ModuleResult
}

func (o *GetModuleInfoByIDOK) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdOK  %+v", 200, o.Payload)
}

func (o *GetModuleInfoByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModuleResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModuleInfoByIDNoContent creates a GetModuleInfoByIDNoContent with default headers values
func NewGetModuleInfoByIDNoContent() *GetModuleInfoByIDNoContent {
	return &GetModuleInfoByIDNoContent{}
}

/*GetModuleInfoByIDNoContent handles this case with default header values.

The request was successful, however no content was returned.
*/
type GetModuleInfoByIDNoContent struct {
}

func (o *GetModuleInfoByIDNoContent) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdNoContent ", 204)
}

func (o *GetModuleInfoByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDPartialContent creates a GetModuleInfoByIDPartialContent with default headers values
func NewGetModuleInfoByIDPartialContent() *GetModuleInfoByIDPartialContent {
	return &GetModuleInfoByIDPartialContent{}
}

/*GetModuleInfoByIDPartialContent handles this case with default header values.

The GET request included a Range Header, and the server responded with the partial content matching the range.
*/
type GetModuleInfoByIDPartialContent struct {
}

func (o *GetModuleInfoByIDPartialContent) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdPartialContent ", 206)
}

func (o *GetModuleInfoByIDPartialContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDBadRequest creates a GetModuleInfoByIDBadRequest with default headers values
func NewGetModuleInfoByIDBadRequest() *GetModuleInfoByIDBadRequest {
	return &GetModuleInfoByIDBadRequest{}
}

/*GetModuleInfoByIDBadRequest handles this case with default header values.

The client made a request that the server could not understand (for example, the request syntax is incorrect).
*/
type GetModuleInfoByIDBadRequest struct {
}

func (o *GetModuleInfoByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdBadRequest ", 400)
}

func (o *GetModuleInfoByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDUnauthorized creates a GetModuleInfoByIDUnauthorized with default headers values
func NewGetModuleInfoByIDUnauthorized() *GetModuleInfoByIDUnauthorized {
	return &GetModuleInfoByIDUnauthorized{}
}

/*GetModuleInfoByIDUnauthorized handles this case with default header values.

The client's authentication credentials included with the request are missing or invalid.
*/
type GetModuleInfoByIDUnauthorized struct {
}

func (o *GetModuleInfoByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdUnauthorized ", 401)
}

func (o *GetModuleInfoByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDForbidden creates a GetModuleInfoByIDForbidden with default headers values
func NewGetModuleInfoByIDForbidden() *GetModuleInfoByIDForbidden {
	return &GetModuleInfoByIDForbidden{}
}

/*GetModuleInfoByIDForbidden handles this case with default header values.

The server recognizes the authentication credentials, but the client is not authorized to perform this request.
*/
type GetModuleInfoByIDForbidden struct {
}

func (o *GetModuleInfoByIDForbidden) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdForbidden ", 403)
}

func (o *GetModuleInfoByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDNotFound creates a GetModuleInfoByIDNotFound with default headers values
func NewGetModuleInfoByIDNotFound() *GetModuleInfoByIDNotFound {
	return &GetModuleInfoByIDNotFound{}
}

/*GetModuleInfoByIDNotFound handles this case with default header values.

The client made a request for a resource that does not exist.
*/
type GetModuleInfoByIDNotFound struct {
}

func (o *GetModuleInfoByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdNotFound ", 404)
}

func (o *GetModuleInfoByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDConflict creates a GetModuleInfoByIDConflict with default headers values
func NewGetModuleInfoByIDConflict() *GetModuleInfoByIDConflict {
	return &GetModuleInfoByIDConflict{}
}

/*GetModuleInfoByIDConflict handles this case with default header values.

The target resource is in a conflicted state (for example, an edit conflict where a resource is being edited by multiple users). Retrying the request later might succeed.
*/
type GetModuleInfoByIDConflict struct {
}

func (o *GetModuleInfoByIDConflict) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdConflict ", 409)
}

func (o *GetModuleInfoByIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDUnsupportedMediaType creates a GetModuleInfoByIDUnsupportedMediaType with default headers values
func NewGetModuleInfoByIDUnsupportedMediaType() *GetModuleInfoByIDUnsupportedMediaType {
	return &GetModuleInfoByIDUnsupportedMediaType{}
}

/*GetModuleInfoByIDUnsupportedMediaType handles this case with default header values.

The client sent a request body in a format that the server does not support (for example, XML to a server that only accepts JSON).
*/
type GetModuleInfoByIDUnsupportedMediaType struct {
}

func (o *GetModuleInfoByIDUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdUnsupportedMediaType ", 415)
}

func (o *GetModuleInfoByIDUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDInternalServerError creates a GetModuleInfoByIDInternalServerError with default headers values
func NewGetModuleInfoByIDInternalServerError() *GetModuleInfoByIDInternalServerError {
	return &GetModuleInfoByIDInternalServerError{}
}

/*GetModuleInfoByIDInternalServerError handles this case with default header values.

The server could not fulfill the request.
*/
type GetModuleInfoByIDInternalServerError struct {
}

func (o *GetModuleInfoByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdInternalServerError ", 500)
}

func (o *GetModuleInfoByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDNotImplemented creates a GetModuleInfoByIDNotImplemented with default headers values
func NewGetModuleInfoByIDNotImplemented() *GetModuleInfoByIDNotImplemented {
	return &GetModuleInfoByIDNotImplemented{}
}

/*GetModuleInfoByIDNotImplemented handles this case with default header values.

The server has not implemented the functionality required to fulfill the request.
*/
type GetModuleInfoByIDNotImplemented struct {
}

func (o *GetModuleInfoByIDNotImplemented) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdNotImplemented ", 501)
}

func (o *GetModuleInfoByIDNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDServiceUnavailable creates a GetModuleInfoByIDServiceUnavailable with default headers values
func NewGetModuleInfoByIDServiceUnavailable() *GetModuleInfoByIDServiceUnavailable {
	return &GetModuleInfoByIDServiceUnavailable{}
}

/*GetModuleInfoByIDServiceUnavailable handles this case with default header values.

The server is (temporarily) unavailable.
*/
type GetModuleInfoByIDServiceUnavailable struct {
}

func (o *GetModuleInfoByIDServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdServiceUnavailable ", 503)
}

func (o *GetModuleInfoByIDServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetModuleInfoByIDGatewayTimeout creates a GetModuleInfoByIDGatewayTimeout with default headers values
func NewGetModuleInfoByIDGatewayTimeout() *GetModuleInfoByIDGatewayTimeout {
	return &GetModuleInfoByIDGatewayTimeout{}
}

/*GetModuleInfoByIDGatewayTimeout handles this case with default header values.

The server did not respond inside time restrictions and timed-out.
*/
type GetModuleInfoByIDGatewayTimeout struct {
}

func (o *GetModuleInfoByIDGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/module/{id}][%d] getModuleInfoByIdGatewayTimeout ", 504)
}

func (o *GetModuleInfoByIDGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
