// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kszafran/junction-2018/models"
)

// GetFunctionalCapabilityForDevicesReader is a Reader for the GetFunctionalCapabilityForDevices structure.
type GetFunctionalCapabilityForDevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFunctionalCapabilityForDevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetFunctionalCapabilityForDevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetFunctionalCapabilityForDevicesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 206:
		result := NewGetFunctionalCapabilityForDevicesPartialContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetFunctionalCapabilityForDevicesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetFunctionalCapabilityForDevicesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetFunctionalCapabilityForDevicesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetFunctionalCapabilityForDevicesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetFunctionalCapabilityForDevicesConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewGetFunctionalCapabilityForDevicesUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetFunctionalCapabilityForDevicesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 501:
		result := NewGetFunctionalCapabilityForDevicesNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewGetFunctionalCapabilityForDevicesServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 504:
		result := NewGetFunctionalCapabilityForDevicesGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetFunctionalCapabilityForDevicesOK creates a GetFunctionalCapabilityForDevicesOK with default headers values
func NewGetFunctionalCapabilityForDevicesOK() *GetFunctionalCapabilityForDevicesOK {
	return &GetFunctionalCapabilityForDevicesOK{}
}

/*GetFunctionalCapabilityForDevicesOK handles this case with default header values.

The request was successful. The result is contained in the response body.
*/
type GetFunctionalCapabilityForDevicesOK struct {
	Payload *models.FunctionalCapabilityListResult
}

func (o *GetFunctionalCapabilityForDevicesOK) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesOK  %+v", 200, o.Payload)
}

func (o *GetFunctionalCapabilityForDevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FunctionalCapabilityListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFunctionalCapabilityForDevicesNoContent creates a GetFunctionalCapabilityForDevicesNoContent with default headers values
func NewGetFunctionalCapabilityForDevicesNoContent() *GetFunctionalCapabilityForDevicesNoContent {
	return &GetFunctionalCapabilityForDevicesNoContent{}
}

/*GetFunctionalCapabilityForDevicesNoContent handles this case with default header values.

The request was successful, however no content was returned.
*/
type GetFunctionalCapabilityForDevicesNoContent struct {
}

func (o *GetFunctionalCapabilityForDevicesNoContent) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesNoContent ", 204)
}

func (o *GetFunctionalCapabilityForDevicesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesPartialContent creates a GetFunctionalCapabilityForDevicesPartialContent with default headers values
func NewGetFunctionalCapabilityForDevicesPartialContent() *GetFunctionalCapabilityForDevicesPartialContent {
	return &GetFunctionalCapabilityForDevicesPartialContent{}
}

/*GetFunctionalCapabilityForDevicesPartialContent handles this case with default header values.

The GET request included a Range Header, and the server responded with the partial content matching the range.
*/
type GetFunctionalCapabilityForDevicesPartialContent struct {
}

func (o *GetFunctionalCapabilityForDevicesPartialContent) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesPartialContent ", 206)
}

func (o *GetFunctionalCapabilityForDevicesPartialContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesBadRequest creates a GetFunctionalCapabilityForDevicesBadRequest with default headers values
func NewGetFunctionalCapabilityForDevicesBadRequest() *GetFunctionalCapabilityForDevicesBadRequest {
	return &GetFunctionalCapabilityForDevicesBadRequest{}
}

/*GetFunctionalCapabilityForDevicesBadRequest handles this case with default header values.

The client made a request that the server could not understand (for example, the request syntax is incorrect).
*/
type GetFunctionalCapabilityForDevicesBadRequest struct {
}

func (o *GetFunctionalCapabilityForDevicesBadRequest) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesBadRequest ", 400)
}

func (o *GetFunctionalCapabilityForDevicesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesUnauthorized creates a GetFunctionalCapabilityForDevicesUnauthorized with default headers values
func NewGetFunctionalCapabilityForDevicesUnauthorized() *GetFunctionalCapabilityForDevicesUnauthorized {
	return &GetFunctionalCapabilityForDevicesUnauthorized{}
}

/*GetFunctionalCapabilityForDevicesUnauthorized handles this case with default header values.

The client's authentication credentials included with the request are missing or invalid.
*/
type GetFunctionalCapabilityForDevicesUnauthorized struct {
}

func (o *GetFunctionalCapabilityForDevicesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesUnauthorized ", 401)
}

func (o *GetFunctionalCapabilityForDevicesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesForbidden creates a GetFunctionalCapabilityForDevicesForbidden with default headers values
func NewGetFunctionalCapabilityForDevicesForbidden() *GetFunctionalCapabilityForDevicesForbidden {
	return &GetFunctionalCapabilityForDevicesForbidden{}
}

/*GetFunctionalCapabilityForDevicesForbidden handles this case with default header values.

The server recognizes the authentication credentials, but the client is not authorized to perform this request.
*/
type GetFunctionalCapabilityForDevicesForbidden struct {
}

func (o *GetFunctionalCapabilityForDevicesForbidden) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesForbidden ", 403)
}

func (o *GetFunctionalCapabilityForDevicesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesNotFound creates a GetFunctionalCapabilityForDevicesNotFound with default headers values
func NewGetFunctionalCapabilityForDevicesNotFound() *GetFunctionalCapabilityForDevicesNotFound {
	return &GetFunctionalCapabilityForDevicesNotFound{}
}

/*GetFunctionalCapabilityForDevicesNotFound handles this case with default header values.

The client made a request for a resource that does not exist.
*/
type GetFunctionalCapabilityForDevicesNotFound struct {
}

func (o *GetFunctionalCapabilityForDevicesNotFound) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesNotFound ", 404)
}

func (o *GetFunctionalCapabilityForDevicesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesConflict creates a GetFunctionalCapabilityForDevicesConflict with default headers values
func NewGetFunctionalCapabilityForDevicesConflict() *GetFunctionalCapabilityForDevicesConflict {
	return &GetFunctionalCapabilityForDevicesConflict{}
}

/*GetFunctionalCapabilityForDevicesConflict handles this case with default header values.

The target resource is in a conflicted state (for example, an edit conflict where a resource is being edited by multiple users). Retrying the request later might succeed.
*/
type GetFunctionalCapabilityForDevicesConflict struct {
}

func (o *GetFunctionalCapabilityForDevicesConflict) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesConflict ", 409)
}

func (o *GetFunctionalCapabilityForDevicesConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesUnsupportedMediaType creates a GetFunctionalCapabilityForDevicesUnsupportedMediaType with default headers values
func NewGetFunctionalCapabilityForDevicesUnsupportedMediaType() *GetFunctionalCapabilityForDevicesUnsupportedMediaType {
	return &GetFunctionalCapabilityForDevicesUnsupportedMediaType{}
}

/*GetFunctionalCapabilityForDevicesUnsupportedMediaType handles this case with default header values.

The client sent a request body in a format that the server does not support (for example, XML to a server that only accepts JSON).
*/
type GetFunctionalCapabilityForDevicesUnsupportedMediaType struct {
}

func (o *GetFunctionalCapabilityForDevicesUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesUnsupportedMediaType ", 415)
}

func (o *GetFunctionalCapabilityForDevicesUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesInternalServerError creates a GetFunctionalCapabilityForDevicesInternalServerError with default headers values
func NewGetFunctionalCapabilityForDevicesInternalServerError() *GetFunctionalCapabilityForDevicesInternalServerError {
	return &GetFunctionalCapabilityForDevicesInternalServerError{}
}

/*GetFunctionalCapabilityForDevicesInternalServerError handles this case with default header values.

The server could not fulfill the request.
*/
type GetFunctionalCapabilityForDevicesInternalServerError struct {
}

func (o *GetFunctionalCapabilityForDevicesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesInternalServerError ", 500)
}

func (o *GetFunctionalCapabilityForDevicesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesNotImplemented creates a GetFunctionalCapabilityForDevicesNotImplemented with default headers values
func NewGetFunctionalCapabilityForDevicesNotImplemented() *GetFunctionalCapabilityForDevicesNotImplemented {
	return &GetFunctionalCapabilityForDevicesNotImplemented{}
}

/*GetFunctionalCapabilityForDevicesNotImplemented handles this case with default header values.

The server has not implemented the functionality required to fulfill the request.
*/
type GetFunctionalCapabilityForDevicesNotImplemented struct {
}

func (o *GetFunctionalCapabilityForDevicesNotImplemented) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesNotImplemented ", 501)
}

func (o *GetFunctionalCapabilityForDevicesNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesServiceUnavailable creates a GetFunctionalCapabilityForDevicesServiceUnavailable with default headers values
func NewGetFunctionalCapabilityForDevicesServiceUnavailable() *GetFunctionalCapabilityForDevicesServiceUnavailable {
	return &GetFunctionalCapabilityForDevicesServiceUnavailable{}
}

/*GetFunctionalCapabilityForDevicesServiceUnavailable handles this case with default header values.

The server is (temporarily) unavailable.
*/
type GetFunctionalCapabilityForDevicesServiceUnavailable struct {
}

func (o *GetFunctionalCapabilityForDevicesServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesServiceUnavailable ", 503)
}

func (o *GetFunctionalCapabilityForDevicesServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFunctionalCapabilityForDevicesGatewayTimeout creates a GetFunctionalCapabilityForDevicesGatewayTimeout with default headers values
func NewGetFunctionalCapabilityForDevicesGatewayTimeout() *GetFunctionalCapabilityForDevicesGatewayTimeout {
	return &GetFunctionalCapabilityForDevicesGatewayTimeout{}
}

/*GetFunctionalCapabilityForDevicesGatewayTimeout handles this case with default header values.

The server did not respond inside time restrictions and timed-out.
*/
type GetFunctionalCapabilityForDevicesGatewayTimeout struct {
}

func (o *GetFunctionalCapabilityForDevicesGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/functional-capability][%d] getFunctionalCapabilityForDevicesGatewayTimeout ", 504)
}

func (o *GetFunctionalCapabilityForDevicesGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
