// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kszafran/junction-2018/models"
)

// GetInterfaceByIDReader is a Reader for the GetInterfaceByID structure.
type GetInterfaceByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInterfaceByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInterfaceByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetInterfaceByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 206:
		result := NewGetInterfaceByIDPartialContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetInterfaceByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetInterfaceByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetInterfaceByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetInterfaceByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetInterfaceByIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewGetInterfaceByIDUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetInterfaceByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 501:
		result := NewGetInterfaceByIDNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewGetInterfaceByIDServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 504:
		result := NewGetInterfaceByIDGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInterfaceByIDOK creates a GetInterfaceByIDOK with default headers values
func NewGetInterfaceByIDOK() *GetInterfaceByIDOK {
	return &GetInterfaceByIDOK{}
}

/*GetInterfaceByIDOK handles this case with default header values.

The request was successful. The result is contained in the response body.
*/
type GetInterfaceByIDOK struct {
	Payload *models.DeviceIfResult
}

func (o *GetInterfaceByIDOK) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdOK  %+v", 200, o.Payload)
}

func (o *GetInterfaceByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceIfResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInterfaceByIDNoContent creates a GetInterfaceByIDNoContent with default headers values
func NewGetInterfaceByIDNoContent() *GetInterfaceByIDNoContent {
	return &GetInterfaceByIDNoContent{}
}

/*GetInterfaceByIDNoContent handles this case with default header values.

The request was successful, however no content was returned.
*/
type GetInterfaceByIDNoContent struct {
}

func (o *GetInterfaceByIDNoContent) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdNoContent ", 204)
}

func (o *GetInterfaceByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDPartialContent creates a GetInterfaceByIDPartialContent with default headers values
func NewGetInterfaceByIDPartialContent() *GetInterfaceByIDPartialContent {
	return &GetInterfaceByIDPartialContent{}
}

/*GetInterfaceByIDPartialContent handles this case with default header values.

The GET request included a Range Header, and the server responded with the partial content matching the range.
*/
type GetInterfaceByIDPartialContent struct {
}

func (o *GetInterfaceByIDPartialContent) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdPartialContent ", 206)
}

func (o *GetInterfaceByIDPartialContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDBadRequest creates a GetInterfaceByIDBadRequest with default headers values
func NewGetInterfaceByIDBadRequest() *GetInterfaceByIDBadRequest {
	return &GetInterfaceByIDBadRequest{}
}

/*GetInterfaceByIDBadRequest handles this case with default header values.

The client made a request that the server could not understand (for example, the request syntax is incorrect).
*/
type GetInterfaceByIDBadRequest struct {
}

func (o *GetInterfaceByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdBadRequest ", 400)
}

func (o *GetInterfaceByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDUnauthorized creates a GetInterfaceByIDUnauthorized with default headers values
func NewGetInterfaceByIDUnauthorized() *GetInterfaceByIDUnauthorized {
	return &GetInterfaceByIDUnauthorized{}
}

/*GetInterfaceByIDUnauthorized handles this case with default header values.

The client's authentication credentials included with the request are missing or invalid.
*/
type GetInterfaceByIDUnauthorized struct {
}

func (o *GetInterfaceByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdUnauthorized ", 401)
}

func (o *GetInterfaceByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDForbidden creates a GetInterfaceByIDForbidden with default headers values
func NewGetInterfaceByIDForbidden() *GetInterfaceByIDForbidden {
	return &GetInterfaceByIDForbidden{}
}

/*GetInterfaceByIDForbidden handles this case with default header values.

The server recognizes the authentication credentials, but the client is not authorized to perform this request.
*/
type GetInterfaceByIDForbidden struct {
}

func (o *GetInterfaceByIDForbidden) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdForbidden ", 403)
}

func (o *GetInterfaceByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDNotFound creates a GetInterfaceByIDNotFound with default headers values
func NewGetInterfaceByIDNotFound() *GetInterfaceByIDNotFound {
	return &GetInterfaceByIDNotFound{}
}

/*GetInterfaceByIDNotFound handles this case with default header values.

The client made a request for a resource that does not exist.
*/
type GetInterfaceByIDNotFound struct {
}

func (o *GetInterfaceByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdNotFound ", 404)
}

func (o *GetInterfaceByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDConflict creates a GetInterfaceByIDConflict with default headers values
func NewGetInterfaceByIDConflict() *GetInterfaceByIDConflict {
	return &GetInterfaceByIDConflict{}
}

/*GetInterfaceByIDConflict handles this case with default header values.

The target resource is in a conflicted state (for example, an edit conflict where a resource is being edited by multiple users). Retrying the request later might succeed.
*/
type GetInterfaceByIDConflict struct {
}

func (o *GetInterfaceByIDConflict) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdConflict ", 409)
}

func (o *GetInterfaceByIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDUnsupportedMediaType creates a GetInterfaceByIDUnsupportedMediaType with default headers values
func NewGetInterfaceByIDUnsupportedMediaType() *GetInterfaceByIDUnsupportedMediaType {
	return &GetInterfaceByIDUnsupportedMediaType{}
}

/*GetInterfaceByIDUnsupportedMediaType handles this case with default header values.

The client sent a request body in a format that the server does not support (for example, XML to a server that only accepts JSON).
*/
type GetInterfaceByIDUnsupportedMediaType struct {
}

func (o *GetInterfaceByIDUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdUnsupportedMediaType ", 415)
}

func (o *GetInterfaceByIDUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDInternalServerError creates a GetInterfaceByIDInternalServerError with default headers values
func NewGetInterfaceByIDInternalServerError() *GetInterfaceByIDInternalServerError {
	return &GetInterfaceByIDInternalServerError{}
}

/*GetInterfaceByIDInternalServerError handles this case with default header values.

The server could not fulfill the request.
*/
type GetInterfaceByIDInternalServerError struct {
}

func (o *GetInterfaceByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdInternalServerError ", 500)
}

func (o *GetInterfaceByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDNotImplemented creates a GetInterfaceByIDNotImplemented with default headers values
func NewGetInterfaceByIDNotImplemented() *GetInterfaceByIDNotImplemented {
	return &GetInterfaceByIDNotImplemented{}
}

/*GetInterfaceByIDNotImplemented handles this case with default header values.

The server has not implemented the functionality required to fulfill the request.
*/
type GetInterfaceByIDNotImplemented struct {
}

func (o *GetInterfaceByIDNotImplemented) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdNotImplemented ", 501)
}

func (o *GetInterfaceByIDNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDServiceUnavailable creates a GetInterfaceByIDServiceUnavailable with default headers values
func NewGetInterfaceByIDServiceUnavailable() *GetInterfaceByIDServiceUnavailable {
	return &GetInterfaceByIDServiceUnavailable{}
}

/*GetInterfaceByIDServiceUnavailable handles this case with default header values.

The server is (temporarily) unavailable.
*/
type GetInterfaceByIDServiceUnavailable struct {
}

func (o *GetInterfaceByIDServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdServiceUnavailable ", 503)
}

func (o *GetInterfaceByIDServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInterfaceByIDGatewayTimeout creates a GetInterfaceByIDGatewayTimeout with default headers values
func NewGetInterfaceByIDGatewayTimeout() *GetInterfaceByIDGatewayTimeout {
	return &GetInterfaceByIDGatewayTimeout{}
}

/*GetInterfaceByIDGatewayTimeout handles this case with default header values.

The server did not respond inside time restrictions and timed-out.
*/
type GetInterfaceByIDGatewayTimeout struct {
}

func (o *GetInterfaceByIDGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/{id}][%d] getInterfaceByIdGatewayTimeout ", 504)
}

func (o *GetInterfaceByIDGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
