// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPollingIntervalByIDParams creates a new GetPollingIntervalByIDParams object
// with the default values initialized.
func NewGetPollingIntervalByIDParams() *GetPollingIntervalByIDParams {
	var ()
	return &GetPollingIntervalByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPollingIntervalByIDParamsWithTimeout creates a new GetPollingIntervalByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPollingIntervalByIDParamsWithTimeout(timeout time.Duration) *GetPollingIntervalByIDParams {
	var ()
	return &GetPollingIntervalByIDParams{

		timeout: timeout,
	}
}

// NewGetPollingIntervalByIDParamsWithContext creates a new GetPollingIntervalByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPollingIntervalByIDParamsWithContext(ctx context.Context) *GetPollingIntervalByIDParams {
	var ()
	return &GetPollingIntervalByIDParams{

		Context: ctx,
	}
}

// NewGetPollingIntervalByIDParamsWithHTTPClient creates a new GetPollingIntervalByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPollingIntervalByIDParamsWithHTTPClient(client *http.Client) *GetPollingIntervalByIDParams {
	var ()
	return &GetPollingIntervalByIDParams{
		HTTPClient: client,
	}
}

/*GetPollingIntervalByIDParams contains all the parameters to send to the API endpoint
for the get polling interval by Id operation typically these are written to a http.Request
*/
type GetPollingIntervalByIDParams struct {

	/*ID
	  Device ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get polling interval by Id params
func (o *GetPollingIntervalByIDParams) WithTimeout(timeout time.Duration) *GetPollingIntervalByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get polling interval by Id params
func (o *GetPollingIntervalByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get polling interval by Id params
func (o *GetPollingIntervalByIDParams) WithContext(ctx context.Context) *GetPollingIntervalByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get polling interval by Id params
func (o *GetPollingIntervalByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get polling interval by Id params
func (o *GetPollingIntervalByIDParams) WithHTTPClient(client *http.Client) *GetPollingIntervalByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get polling interval by Id params
func (o *GetPollingIntervalByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get polling interval by Id params
func (o *GetPollingIntervalByIDParams) WithID(id string) *GetPollingIntervalByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get polling interval by Id params
func (o *GetPollingIntervalByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPollingIntervalByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
