// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kszafran/junction-2018/models"
)

// GetDeviceSummaryReader is a Reader for the GetDeviceSummary structure.
type GetDeviceSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeviceSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDeviceSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetDeviceSummaryNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 206:
		result := NewGetDeviceSummaryPartialContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetDeviceSummaryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetDeviceSummaryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetDeviceSummaryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetDeviceSummaryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetDeviceSummaryConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewGetDeviceSummaryUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetDeviceSummaryInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 501:
		result := NewGetDeviceSummaryNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewGetDeviceSummaryServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 504:
		result := NewGetDeviceSummaryGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDeviceSummaryOK creates a GetDeviceSummaryOK with default headers values
func NewGetDeviceSummaryOK() *GetDeviceSummaryOK {
	return &GetDeviceSummaryOK{}
}

/*GetDeviceSummaryOK handles this case with default header values.

The request was successful. The result is contained in the response body.
*/
type GetDeviceSummaryOK struct {
	Payload *models.NetworkDeviceBriefNIOResult
}

func (o *GetDeviceSummaryOK) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryOK  %+v", 200, o.Payload)
}

func (o *GetDeviceSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkDeviceBriefNIOResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeviceSummaryNoContent creates a GetDeviceSummaryNoContent with default headers values
func NewGetDeviceSummaryNoContent() *GetDeviceSummaryNoContent {
	return &GetDeviceSummaryNoContent{}
}

/*GetDeviceSummaryNoContent handles this case with default header values.

The request was successful, however no content was returned.
*/
type GetDeviceSummaryNoContent struct {
}

func (o *GetDeviceSummaryNoContent) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryNoContent ", 204)
}

func (o *GetDeviceSummaryNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryPartialContent creates a GetDeviceSummaryPartialContent with default headers values
func NewGetDeviceSummaryPartialContent() *GetDeviceSummaryPartialContent {
	return &GetDeviceSummaryPartialContent{}
}

/*GetDeviceSummaryPartialContent handles this case with default header values.

The GET request included a Range Header, and the server responded with the partial content matching the range.
*/
type GetDeviceSummaryPartialContent struct {
}

func (o *GetDeviceSummaryPartialContent) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryPartialContent ", 206)
}

func (o *GetDeviceSummaryPartialContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryBadRequest creates a GetDeviceSummaryBadRequest with default headers values
func NewGetDeviceSummaryBadRequest() *GetDeviceSummaryBadRequest {
	return &GetDeviceSummaryBadRequest{}
}

/*GetDeviceSummaryBadRequest handles this case with default header values.

The client made a request that the server could not understand (for example, the request syntax is incorrect).
*/
type GetDeviceSummaryBadRequest struct {
}

func (o *GetDeviceSummaryBadRequest) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryBadRequest ", 400)
}

func (o *GetDeviceSummaryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryUnauthorized creates a GetDeviceSummaryUnauthorized with default headers values
func NewGetDeviceSummaryUnauthorized() *GetDeviceSummaryUnauthorized {
	return &GetDeviceSummaryUnauthorized{}
}

/*GetDeviceSummaryUnauthorized handles this case with default header values.

The client's authentication credentials included with the request are missing or invalid.
*/
type GetDeviceSummaryUnauthorized struct {
}

func (o *GetDeviceSummaryUnauthorized) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryUnauthorized ", 401)
}

func (o *GetDeviceSummaryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryForbidden creates a GetDeviceSummaryForbidden with default headers values
func NewGetDeviceSummaryForbidden() *GetDeviceSummaryForbidden {
	return &GetDeviceSummaryForbidden{}
}

/*GetDeviceSummaryForbidden handles this case with default header values.

The server recognizes the authentication credentials, but the client is not authorized to perform this request.
*/
type GetDeviceSummaryForbidden struct {
}

func (o *GetDeviceSummaryForbidden) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryForbidden ", 403)
}

func (o *GetDeviceSummaryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryNotFound creates a GetDeviceSummaryNotFound with default headers values
func NewGetDeviceSummaryNotFound() *GetDeviceSummaryNotFound {
	return &GetDeviceSummaryNotFound{}
}

/*GetDeviceSummaryNotFound handles this case with default header values.

The client made a request for a resource that does not exist.
*/
type GetDeviceSummaryNotFound struct {
}

func (o *GetDeviceSummaryNotFound) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryNotFound ", 404)
}

func (o *GetDeviceSummaryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryConflict creates a GetDeviceSummaryConflict with default headers values
func NewGetDeviceSummaryConflict() *GetDeviceSummaryConflict {
	return &GetDeviceSummaryConflict{}
}

/*GetDeviceSummaryConflict handles this case with default header values.

The target resource is in a conflicted state (for example, an edit conflict where a resource is being edited by multiple users). Retrying the request later might succeed.
*/
type GetDeviceSummaryConflict struct {
}

func (o *GetDeviceSummaryConflict) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryConflict ", 409)
}

func (o *GetDeviceSummaryConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryUnsupportedMediaType creates a GetDeviceSummaryUnsupportedMediaType with default headers values
func NewGetDeviceSummaryUnsupportedMediaType() *GetDeviceSummaryUnsupportedMediaType {
	return &GetDeviceSummaryUnsupportedMediaType{}
}

/*GetDeviceSummaryUnsupportedMediaType handles this case with default header values.

The client sent a request body in a format that the server does not support (for example, XML to a server that only accepts JSON).
*/
type GetDeviceSummaryUnsupportedMediaType struct {
}

func (o *GetDeviceSummaryUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryUnsupportedMediaType ", 415)
}

func (o *GetDeviceSummaryUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryInternalServerError creates a GetDeviceSummaryInternalServerError with default headers values
func NewGetDeviceSummaryInternalServerError() *GetDeviceSummaryInternalServerError {
	return &GetDeviceSummaryInternalServerError{}
}

/*GetDeviceSummaryInternalServerError handles this case with default header values.

The server could not fulfill the request.
*/
type GetDeviceSummaryInternalServerError struct {
}

func (o *GetDeviceSummaryInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryInternalServerError ", 500)
}

func (o *GetDeviceSummaryInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryNotImplemented creates a GetDeviceSummaryNotImplemented with default headers values
func NewGetDeviceSummaryNotImplemented() *GetDeviceSummaryNotImplemented {
	return &GetDeviceSummaryNotImplemented{}
}

/*GetDeviceSummaryNotImplemented handles this case with default header values.

The server has not implemented the functionality required to fulfill the request.
*/
type GetDeviceSummaryNotImplemented struct {
}

func (o *GetDeviceSummaryNotImplemented) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryNotImplemented ", 501)
}

func (o *GetDeviceSummaryNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryServiceUnavailable creates a GetDeviceSummaryServiceUnavailable with default headers values
func NewGetDeviceSummaryServiceUnavailable() *GetDeviceSummaryServiceUnavailable {
	return &GetDeviceSummaryServiceUnavailable{}
}

/*GetDeviceSummaryServiceUnavailable handles this case with default header values.

The server is (temporarily) unavailable.
*/
type GetDeviceSummaryServiceUnavailable struct {
}

func (o *GetDeviceSummaryServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryServiceUnavailable ", 503)
}

func (o *GetDeviceSummaryServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeviceSummaryGatewayTimeout creates a GetDeviceSummaryGatewayTimeout with default headers values
func NewGetDeviceSummaryGatewayTimeout() *GetDeviceSummaryGatewayTimeout {
	return &GetDeviceSummaryGatewayTimeout{}
}

/*GetDeviceSummaryGatewayTimeout handles this case with default header values.

The server did not respond inside time restrictions and timed-out.
*/
type GetDeviceSummaryGatewayTimeout struct {
}

func (o *GetDeviceSummaryGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/network-device/{id}/brief][%d] getDeviceSummaryGatewayTimeout ", 504)
}

func (o *GetDeviceSummaryGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
