// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kszafran/junction-2018/models"
)

// GetISISInterfacesReader is a Reader for the GetISISInterfaces structure.
type GetISISInterfacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetISISInterfacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetISISInterfacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewGetISISInterfacesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 206:
		result := NewGetISISInterfacesPartialContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetISISInterfacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetISISInterfacesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetISISInterfacesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetISISInterfacesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetISISInterfacesConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewGetISISInterfacesUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetISISInterfacesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 501:
		result := NewGetISISInterfacesNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewGetISISInterfacesServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 504:
		result := NewGetISISInterfacesGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetISISInterfacesOK creates a GetISISInterfacesOK with default headers values
func NewGetISISInterfacesOK() *GetISISInterfacesOK {
	return &GetISISInterfacesOK{}
}

/*GetISISInterfacesOK handles this case with default header values.

The request was successful. The result is contained in the response body.
*/
type GetISISInterfacesOK struct {
	Payload *models.DeviceIfListResult
}

func (o *GetISISInterfacesOK) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesOK  %+v", 200, o.Payload)
}

func (o *GetISISInterfacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceIfListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetISISInterfacesNoContent creates a GetISISInterfacesNoContent with default headers values
func NewGetISISInterfacesNoContent() *GetISISInterfacesNoContent {
	return &GetISISInterfacesNoContent{}
}

/*GetISISInterfacesNoContent handles this case with default header values.

The request was successful, however no content was returned.
*/
type GetISISInterfacesNoContent struct {
}

func (o *GetISISInterfacesNoContent) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesNoContent ", 204)
}

func (o *GetISISInterfacesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesPartialContent creates a GetISISInterfacesPartialContent with default headers values
func NewGetISISInterfacesPartialContent() *GetISISInterfacesPartialContent {
	return &GetISISInterfacesPartialContent{}
}

/*GetISISInterfacesPartialContent handles this case with default header values.

The GET request included a Range Header, and the server responded with the partial content matching the range.
*/
type GetISISInterfacesPartialContent struct {
}

func (o *GetISISInterfacesPartialContent) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesPartialContent ", 206)
}

func (o *GetISISInterfacesPartialContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesBadRequest creates a GetISISInterfacesBadRequest with default headers values
func NewGetISISInterfacesBadRequest() *GetISISInterfacesBadRequest {
	return &GetISISInterfacesBadRequest{}
}

/*GetISISInterfacesBadRequest handles this case with default header values.

The client made a request that the server could not understand (for example, the request syntax is incorrect).
*/
type GetISISInterfacesBadRequest struct {
}

func (o *GetISISInterfacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesBadRequest ", 400)
}

func (o *GetISISInterfacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesUnauthorized creates a GetISISInterfacesUnauthorized with default headers values
func NewGetISISInterfacesUnauthorized() *GetISISInterfacesUnauthorized {
	return &GetISISInterfacesUnauthorized{}
}

/*GetISISInterfacesUnauthorized handles this case with default header values.

The client's authentication credentials included with the request are missing or invalid.
*/
type GetISISInterfacesUnauthorized struct {
}

func (o *GetISISInterfacesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesUnauthorized ", 401)
}

func (o *GetISISInterfacesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesForbidden creates a GetISISInterfacesForbidden with default headers values
func NewGetISISInterfacesForbidden() *GetISISInterfacesForbidden {
	return &GetISISInterfacesForbidden{}
}

/*GetISISInterfacesForbidden handles this case with default header values.

The server recognizes the authentication credentials, but the client is not authorized to perform this request.
*/
type GetISISInterfacesForbidden struct {
}

func (o *GetISISInterfacesForbidden) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesForbidden ", 403)
}

func (o *GetISISInterfacesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesNotFound creates a GetISISInterfacesNotFound with default headers values
func NewGetISISInterfacesNotFound() *GetISISInterfacesNotFound {
	return &GetISISInterfacesNotFound{}
}

/*GetISISInterfacesNotFound handles this case with default header values.

The client made a request for a resource that does not exist.
*/
type GetISISInterfacesNotFound struct {
}

func (o *GetISISInterfacesNotFound) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesNotFound ", 404)
}

func (o *GetISISInterfacesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesConflict creates a GetISISInterfacesConflict with default headers values
func NewGetISISInterfacesConflict() *GetISISInterfacesConflict {
	return &GetISISInterfacesConflict{}
}

/*GetISISInterfacesConflict handles this case with default header values.

The target resource is in a conflicted state (for example, an edit conflict where a resource is being edited by multiple users). Retrying the request later might succeed.
*/
type GetISISInterfacesConflict struct {
}

func (o *GetISISInterfacesConflict) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesConflict ", 409)
}

func (o *GetISISInterfacesConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesUnsupportedMediaType creates a GetISISInterfacesUnsupportedMediaType with default headers values
func NewGetISISInterfacesUnsupportedMediaType() *GetISISInterfacesUnsupportedMediaType {
	return &GetISISInterfacesUnsupportedMediaType{}
}

/*GetISISInterfacesUnsupportedMediaType handles this case with default header values.

The client sent a request body in a format that the server does not support (for example, XML to a server that only accepts JSON).
*/
type GetISISInterfacesUnsupportedMediaType struct {
}

func (o *GetISISInterfacesUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesUnsupportedMediaType ", 415)
}

func (o *GetISISInterfacesUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesInternalServerError creates a GetISISInterfacesInternalServerError with default headers values
func NewGetISISInterfacesInternalServerError() *GetISISInterfacesInternalServerError {
	return &GetISISInterfacesInternalServerError{}
}

/*GetISISInterfacesInternalServerError handles this case with default header values.

The server could not fulfill the request.
*/
type GetISISInterfacesInternalServerError struct {
}

func (o *GetISISInterfacesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesInternalServerError ", 500)
}

func (o *GetISISInterfacesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesNotImplemented creates a GetISISInterfacesNotImplemented with default headers values
func NewGetISISInterfacesNotImplemented() *GetISISInterfacesNotImplemented {
	return &GetISISInterfacesNotImplemented{}
}

/*GetISISInterfacesNotImplemented handles this case with default header values.

The server has not implemented the functionality required to fulfill the request.
*/
type GetISISInterfacesNotImplemented struct {
}

func (o *GetISISInterfacesNotImplemented) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesNotImplemented ", 501)
}

func (o *GetISISInterfacesNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesServiceUnavailable creates a GetISISInterfacesServiceUnavailable with default headers values
func NewGetISISInterfacesServiceUnavailable() *GetISISInterfacesServiceUnavailable {
	return &GetISISInterfacesServiceUnavailable{}
}

/*GetISISInterfacesServiceUnavailable handles this case with default header values.

The server is (temporarily) unavailable.
*/
type GetISISInterfacesServiceUnavailable struct {
}

func (o *GetISISInterfacesServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesServiceUnavailable ", 503)
}

func (o *GetISISInterfacesServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetISISInterfacesGatewayTimeout creates a GetISISInterfacesGatewayTimeout with default headers values
func NewGetISISInterfacesGatewayTimeout() *GetISISInterfacesGatewayTimeout {
	return &GetISISInterfacesGatewayTimeout{}
}

/*GetISISInterfacesGatewayTimeout handles this case with default header values.

The server did not respond inside time restrictions and timed-out.
*/
type GetISISInterfacesGatewayTimeout struct {
}

func (o *GetISISInterfacesGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /dna/intent/api/v1/interface/isis][%d] getISISInterfacesGatewayTimeout ", 504)
}

func (o *GetISISInterfacesGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
