// Code generated by go-swagger; DO NOT EDIT.

package template_programmer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kszafran/junction-2018/models"
)

// CreateTemplateReader is a Reader for the CreateTemplate structure.
type CreateTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewCreateTemplateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewCreateTemplateAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewCreateTemplateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 206:
		result := NewCreateTemplatePartialContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateTemplateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCreateTemplateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateTemplateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreateTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewCreateTemplateConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewCreateTemplateUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreateTemplateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 501:
		result := NewCreateTemplateNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewCreateTemplateServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 504:
		result := NewCreateTemplateGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateTemplateOK creates a CreateTemplateOK with default headers values
func NewCreateTemplateOK() *CreateTemplateOK {
	return &CreateTemplateOK{}
}

/*CreateTemplateOK handles this case with default header values.

The request was successful. The result is contained in the response body.
*/
type CreateTemplateOK struct {
	Payload *models.TaskIDResult
}

func (o *CreateTemplateOK) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateOK  %+v", 200, o.Payload)
}

func (o *CreateTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TaskIDResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTemplateCreated creates a CreateTemplateCreated with default headers values
func NewCreateTemplateCreated() *CreateTemplateCreated {
	return &CreateTemplateCreated{}
}

/*CreateTemplateCreated handles this case with default header values.

The POST/PUT request was fulfilled and a new resource has been created. Information about the resource is in the response body.
*/
type CreateTemplateCreated struct {
}

func (o *CreateTemplateCreated) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateCreated ", 201)
}

func (o *CreateTemplateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateAccepted creates a CreateTemplateAccepted with default headers values
func NewCreateTemplateAccepted() *CreateTemplateAccepted {
	return &CreateTemplateAccepted{}
}

/*CreateTemplateAccepted handles this case with default header values.

The request was accepted for processing, but the processing has not been completed.
*/
type CreateTemplateAccepted struct {
}

func (o *CreateTemplateAccepted) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateAccepted ", 202)
}

func (o *CreateTemplateAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateNoContent creates a CreateTemplateNoContent with default headers values
func NewCreateTemplateNoContent() *CreateTemplateNoContent {
	return &CreateTemplateNoContent{}
}

/*CreateTemplateNoContent handles this case with default header values.

The request was successful, however no content was returned.
*/
type CreateTemplateNoContent struct {
}

func (o *CreateTemplateNoContent) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateNoContent ", 204)
}

func (o *CreateTemplateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplatePartialContent creates a CreateTemplatePartialContent with default headers values
func NewCreateTemplatePartialContent() *CreateTemplatePartialContent {
	return &CreateTemplatePartialContent{}
}

/*CreateTemplatePartialContent handles this case with default header values.

The GET request included a Range Header, and the server responded with the partial content matching the range.
*/
type CreateTemplatePartialContent struct {
}

func (o *CreateTemplatePartialContent) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplatePartialContent ", 206)
}

func (o *CreateTemplatePartialContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateBadRequest creates a CreateTemplateBadRequest with default headers values
func NewCreateTemplateBadRequest() *CreateTemplateBadRequest {
	return &CreateTemplateBadRequest{}
}

/*CreateTemplateBadRequest handles this case with default header values.

The client made a request that the server could not understand (for example, the request syntax is incorrect).
*/
type CreateTemplateBadRequest struct {
}

func (o *CreateTemplateBadRequest) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateBadRequest ", 400)
}

func (o *CreateTemplateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateUnauthorized creates a CreateTemplateUnauthorized with default headers values
func NewCreateTemplateUnauthorized() *CreateTemplateUnauthorized {
	return &CreateTemplateUnauthorized{}
}

/*CreateTemplateUnauthorized handles this case with default header values.

The client's authentication credentials included with the request are missing or invalid.
*/
type CreateTemplateUnauthorized struct {
}

func (o *CreateTemplateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateUnauthorized ", 401)
}

func (o *CreateTemplateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateForbidden creates a CreateTemplateForbidden with default headers values
func NewCreateTemplateForbidden() *CreateTemplateForbidden {
	return &CreateTemplateForbidden{}
}

/*CreateTemplateForbidden handles this case with default header values.

The server recognizes the authentication credentials, but the client is not authorized to perform this request.
*/
type CreateTemplateForbidden struct {
}

func (o *CreateTemplateForbidden) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateForbidden ", 403)
}

func (o *CreateTemplateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateNotFound creates a CreateTemplateNotFound with default headers values
func NewCreateTemplateNotFound() *CreateTemplateNotFound {
	return &CreateTemplateNotFound{}
}

/*CreateTemplateNotFound handles this case with default header values.

The client made a request for a resource that does not exist.
*/
type CreateTemplateNotFound struct {
}

func (o *CreateTemplateNotFound) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateNotFound ", 404)
}

func (o *CreateTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateConflict creates a CreateTemplateConflict with default headers values
func NewCreateTemplateConflict() *CreateTemplateConflict {
	return &CreateTemplateConflict{}
}

/*CreateTemplateConflict handles this case with default header values.

The target resource is in a conflicted state (for example, an edit conflict where a resource is being edited by multiple users). Retrying the request later might succeed.
*/
type CreateTemplateConflict struct {
}

func (o *CreateTemplateConflict) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateConflict ", 409)
}

func (o *CreateTemplateConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateUnsupportedMediaType creates a CreateTemplateUnsupportedMediaType with default headers values
func NewCreateTemplateUnsupportedMediaType() *CreateTemplateUnsupportedMediaType {
	return &CreateTemplateUnsupportedMediaType{}
}

/*CreateTemplateUnsupportedMediaType handles this case with default header values.

The client sent a request body in a format that the server does not support (for example, XML to a server that only accepts JSON).
*/
type CreateTemplateUnsupportedMediaType struct {
}

func (o *CreateTemplateUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateUnsupportedMediaType ", 415)
}

func (o *CreateTemplateUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateInternalServerError creates a CreateTemplateInternalServerError with default headers values
func NewCreateTemplateInternalServerError() *CreateTemplateInternalServerError {
	return &CreateTemplateInternalServerError{}
}

/*CreateTemplateInternalServerError handles this case with default header values.

The server could not fulfill the request.
*/
type CreateTemplateInternalServerError struct {
}

func (o *CreateTemplateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateInternalServerError ", 500)
}

func (o *CreateTemplateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateNotImplemented creates a CreateTemplateNotImplemented with default headers values
func NewCreateTemplateNotImplemented() *CreateTemplateNotImplemented {
	return &CreateTemplateNotImplemented{}
}

/*CreateTemplateNotImplemented handles this case with default header values.

The server has not implemented the functionality required to fulfill the request.
*/
type CreateTemplateNotImplemented struct {
}

func (o *CreateTemplateNotImplemented) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateNotImplemented ", 501)
}

func (o *CreateTemplateNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateServiceUnavailable creates a CreateTemplateServiceUnavailable with default headers values
func NewCreateTemplateServiceUnavailable() *CreateTemplateServiceUnavailable {
	return &CreateTemplateServiceUnavailable{}
}

/*CreateTemplateServiceUnavailable handles this case with default header values.

The server is (temporarily) unavailable.
*/
type CreateTemplateServiceUnavailable struct {
}

func (o *CreateTemplateServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateServiceUnavailable ", 503)
}

func (o *CreateTemplateServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateTemplateGatewayTimeout creates a CreateTemplateGatewayTimeout with default headers values
func NewCreateTemplateGatewayTimeout() *CreateTemplateGatewayTimeout {
	return &CreateTemplateGatewayTimeout{}
}

/*CreateTemplateGatewayTimeout handles this case with default header values.

The server did not respond inside time restrictions and timed-out.
*/
type CreateTemplateGatewayTimeout struct {
}

func (o *CreateTemplateGatewayTimeout) Error() string {
	return fmt.Sprintf("[POST /dna/intent/api/v1/template-programmer/project/{projectId}/template][%d] createTemplateGatewayTimeout ", 504)
}

func (o *CreateTemplateGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
