// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVLANDetailsParams creates a new GetVLANDetailsParams object
// with the default values initialized.
func NewGetVLANDetailsParams() *GetVLANDetailsParams {

	return &GetVLANDetailsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVLANDetailsParamsWithTimeout creates a new GetVLANDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVLANDetailsParamsWithTimeout(timeout time.Duration) *GetVLANDetailsParams {

	return &GetVLANDetailsParams{

		timeout: timeout,
	}
}

// NewGetVLANDetailsParamsWithContext creates a new GetVLANDetailsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVLANDetailsParamsWithContext(ctx context.Context) *GetVLANDetailsParams {

	return &GetVLANDetailsParams{

		Context: ctx,
	}
}

// NewGetVLANDetailsParamsWithHTTPClient creates a new GetVLANDetailsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVLANDetailsParamsWithHTTPClient(client *http.Client) *GetVLANDetailsParams {

	return &GetVLANDetailsParams{
		HTTPClient: client,
	}
}

/*GetVLANDetailsParams contains all the parameters to send to the API endpoint
for the get v l a n details operation typically these are written to a http.Request
*/
type GetVLANDetailsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v l a n details params
func (o *GetVLANDetailsParams) WithTimeout(timeout time.Duration) *GetVLANDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v l a n details params
func (o *GetVLANDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v l a n details params
func (o *GetVLANDetailsParams) WithContext(ctx context.Context) *GetVLANDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v l a n details params
func (o *GetVLANDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v l a n details params
func (o *GetVLANDetailsParams) WithHTTPClient(client *http.Client) *GetVLANDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v l a n details params
func (o *GetVLANDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetVLANDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
