// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOverallNetworkHealthParams creates a new GetOverallNetworkHealthParams object
// with the default values initialized.
func NewGetOverallNetworkHealthParams() *GetOverallNetworkHealthParams {
	var (
		persistbapioutputDefault = bool(true)
		runsyncDefault           = bool(true)
		timeoutDefault           = float64(30)
		timestampDefault         = string("1542990102")
	)
	return &GetOverallNetworkHealthParams{
		Persistbapioutput: persistbapioutputDefault,
		Runsync:           runsyncDefault,
		Timeout:           timeoutDefault,
		Timestamp:         timestampDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOverallNetworkHealthParamsWithTimeout creates a new GetOverallNetworkHealthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOverallNetworkHealthParamsWithTimeout(timeout time.Duration) *GetOverallNetworkHealthParams {
	var (
		persistbapioutputDefault = bool(true)
		runsyncDefault           = bool(true)
		timeoutDefault           = float64(30)
		timestampDefault         = string("1542990102")
	)
	return &GetOverallNetworkHealthParams{
		Persistbapioutput: persistbapioutputDefault,
		Runsync:           runsyncDefault,
		Timeout:           timeoutDefault,
		Timestamp:         timestampDefault,

		timeout: timeout,
	}
}

// NewGetOverallNetworkHealthParamsWithContext creates a new GetOverallNetworkHealthParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOverallNetworkHealthParamsWithContext(ctx context.Context) *GetOverallNetworkHealthParams {
	var (
		persistbapioutputDefault = bool(true)
		runsyncDefault           = bool(true)
		timeoutDefault           = float64(30)
		timestampDefault         = string("1542990102")
	)
	return &GetOverallNetworkHealthParams{
		Persistbapioutput: persistbapioutputDefault,
		Runsync:           runsyncDefault,
		Timeout:           timeoutDefault,
		Timestamp:         timestampDefault,

		Context: ctx,
	}
}

// NewGetOverallNetworkHealthParamsWithHTTPClient creates a new GetOverallNetworkHealthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOverallNetworkHealthParamsWithHTTPClient(client *http.Client) *GetOverallNetworkHealthParams {
	var (
		persistbapioutputDefault = bool(true)
		runsyncDefault           = bool(true)
		timeoutDefault           = float64(30)
		timestampDefault         = string("1542990102")
	)
	return &GetOverallNetworkHealthParams{
		Persistbapioutput: persistbapioutputDefault,
		Runsync:           runsyncDefault,
		Timeout:           timeoutDefault,
		Timestamp:         timestampDefault,
		HTTPClient:        client,
	}
}

/*GetOverallNetworkHealthParams contains all the parameters to send to the API endpoint
for the get overall network health operation typically these are written to a http.Request
*/
type GetOverallNetworkHealthParams struct {

	/*Persistbapioutput
	  Enable this parameter to ensure that the synchronous response of the API is made available as part of the logs and the execution status

	*/
	Persistbapioutput bool
	/*Runsync
	  Enable this parameter to execute the API and return a response synchronously

	*/
	Runsync bool
	/*Timeout
	  If __runsync is set to ‘true’, this defines the maximum time before which if the API completes its execution, then a synchronous response is returned.  If the time taken for the API to complete the execution, exceeds this time, then an asynchronous response is returned with an execution id, that can be used to get the status and response associated with the API execution

	*/
	Timeout float64
	/*Timestamp
	  Epoch time(in milliseconds) when the Network health data is required

	*/
	Timestamp string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get overall network health params
func (o *GetOverallNetworkHealthParams) WithTimeout(timeout time.Duration) *GetOverallNetworkHealthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get overall network health params
func (o *GetOverallNetworkHealthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get overall network health params
func (o *GetOverallNetworkHealthParams) WithContext(ctx context.Context) *GetOverallNetworkHealthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get overall network health params
func (o *GetOverallNetworkHealthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get overall network health params
func (o *GetOverallNetworkHealthParams) WithHTTPClient(client *http.Client) *GetOverallNetworkHealthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get overall network health params
func (o *GetOverallNetworkHealthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPersistbapioutput adds the persistbapioutput to the get overall network health params
func (o *GetOverallNetworkHealthParams) WithPersistbapioutput(persistbapioutput bool) *GetOverallNetworkHealthParams {
	o.SetPersistbapioutput(persistbapioutput)
	return o
}

// SetPersistbapioutput adds the persistbapioutput to the get overall network health params
func (o *GetOverallNetworkHealthParams) SetPersistbapioutput(persistbapioutput bool) {
	o.Persistbapioutput = persistbapioutput
}

// WithRunsync adds the runsync to the get overall network health params
func (o *GetOverallNetworkHealthParams) WithRunsync(runsync bool) *GetOverallNetworkHealthParams {
	o.SetRunsync(runsync)
	return o
}

// SetRunsync adds the runsync to the get overall network health params
func (o *GetOverallNetworkHealthParams) SetRunsync(runsync bool) {
	o.Runsync = runsync
}

// WithTimeout adds the timeout to the get overall network health params
func (o *GetOverallNetworkHealthParams) WithTimeout(timeout float64) *GetOverallNetworkHealthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get overall network health params
func (o *GetOverallNetworkHealthParams) SetTimeout(timeout float64) {
	o.Timeout = timeout
}

// WithTimestamp adds the timestamp to the get overall network health params
func (o *GetOverallNetworkHealthParams) WithTimestamp(timestamp string) *GetOverallNetworkHealthParams {
	o.SetTimestamp(timestamp)
	return o
}

// SetTimestamp adds the timestamp to the get overall network health params
func (o *GetOverallNetworkHealthParams) SetTimestamp(timestamp string) {
	o.Timestamp = timestamp
}

// WriteToRequest writes these params to a swagger request
func (o *GetOverallNetworkHealthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param __persistbapioutput
	if err := r.SetHeaderParam("__persistbapioutput", swag.FormatBool(o.Persistbapioutput)); err != nil {
		return err
	}

	// header param __runsync
	if err := r.SetHeaderParam("__runsync", swag.FormatBool(o.Runsync)); err != nil {
		return err
	}

	// header param __timeout
	if err := r.SetHeaderParam("__timeout", swag.FormatFloat64(o.Timeout)); err != nil {
		return err
	}

	// query param timestamp
	qrTimestamp := o.Timestamp
	qTimestamp := qrTimestamp
	if qTimestamp != "" {
		if err := r.SetQueryParam("timestamp", qTimestamp); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
