// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kszafran/junction-2018/models"
)

// CreateSiteReader is a Reader for the CreateSite structure.
type CreateSiteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSiteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateSiteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateSiteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCreateSiteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreateSiteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreateSiteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateSiteOK creates a CreateSiteOK with default headers values
func NewCreateSiteOK() *CreateSiteOK {
	return &CreateSiteOK{}
}

/*CreateSiteOK handles this case with default header values.

The request was successful. The result is contained in the response body.
*/
type CreateSiteOK struct {
	Payload *models.CreateSiteResponse
}

func (o *CreateSiteOK) Error() string {
	return fmt.Sprintf("[POST /dna/system/api/v1/site][%d] createSiteOK  %+v", 200, o.Payload)
}

func (o *CreateSiteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateSiteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSiteBadRequest creates a CreateSiteBadRequest with default headers values
func NewCreateSiteBadRequest() *CreateSiteBadRequest {
	return &CreateSiteBadRequest{}
}

/*CreateSiteBadRequest handles this case with default header values.

The client made a request that the server could not understand (for example, the request syntax is incorrect).
*/
type CreateSiteBadRequest struct {
}

func (o *CreateSiteBadRequest) Error() string {
	return fmt.Sprintf("[POST /dna/system/api/v1/site][%d] createSiteBadRequest ", 400)
}

func (o *CreateSiteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSiteUnauthorized creates a CreateSiteUnauthorized with default headers values
func NewCreateSiteUnauthorized() *CreateSiteUnauthorized {
	return &CreateSiteUnauthorized{}
}

/*CreateSiteUnauthorized handles this case with default header values.

The client's authentication credentials included with the request are missing or invalid.
*/
type CreateSiteUnauthorized struct {
}

func (o *CreateSiteUnauthorized) Error() string {
	return fmt.Sprintf("[POST /dna/system/api/v1/site][%d] createSiteUnauthorized ", 401)
}

func (o *CreateSiteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSiteNotFound creates a CreateSiteNotFound with default headers values
func NewCreateSiteNotFound() *CreateSiteNotFound {
	return &CreateSiteNotFound{}
}

/*CreateSiteNotFound handles this case with default header values.

The client made a request for a resource that does not exist.
*/
type CreateSiteNotFound struct {
}

func (o *CreateSiteNotFound) Error() string {
	return fmt.Sprintf("[POST /dna/system/api/v1/site][%d] createSiteNotFound ", 404)
}

func (o *CreateSiteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSiteInternalServerError creates a CreateSiteInternalServerError with default headers values
func NewCreateSiteInternalServerError() *CreateSiteInternalServerError {
	return &CreateSiteInternalServerError{}
}

/*CreateSiteInternalServerError handles this case with default header values.

The server could not fulfill the request.
*/
type CreateSiteInternalServerError struct {
}

func (o *CreateSiteInternalServerError) Error() string {
	return fmt.Sprintf("[POST /dna/system/api/v1/site][%d] createSiteInternalServerError ", 500)
}

func (o *CreateSiteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
