package main

import (
	"crypto/tls"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)

func main() {
	// this example was almost fully generated by postman
	// this disables the security checks (they've got bad ssl certificate)
	http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}

	url := "https://82.203.192.245/dna/system/api/v1/auth/token"

	req, err := http.NewRequest("POST", url, nil)

	if err != nil {
		log.Fatalf("got error, 1: %v", err)
	}

	req.Header.Add("Content-Type", "application/json")
	req.Header.Add("Authorization", "Basic ZGV2ZWxvcGVyOkhhY2tqdW5jdGlvbjIwMTg=")
	req.Header.Add("cache-control", "no-cache")
	req.Header.Add("Postman-Token", "7b9260d2-058d-4a6b-b165-c66cd563a474")

	res, err := http.DefaultClient.Do(req)

	if err != nil {
		log.Fatalf("got error, 2: %v", err)
	}

	defer res.Body.Close()
	body, err := ioutil.ReadAll(res.Body)

	if err != nil {
		log.Fatalf("got error, 3: %v", err)
	}

	fmt.Println(res)
	fmt.Println(string(body))

}
