// Code generated by go-swagger; DO NOT EDIT.

package pn_p

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWorkflowByIDParams creates a new GetWorkflowByIDParams object
// with the default values initialized.
func NewGetWorkflowByIDParams() *GetWorkflowByIDParams {
	var ()
	return &GetWorkflowByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowByIDParamsWithTimeout creates a new GetWorkflowByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkflowByIDParamsWithTimeout(timeout time.Duration) *GetWorkflowByIDParams {
	var ()
	return &GetWorkflowByIDParams{

		timeout: timeout,
	}
}

// NewGetWorkflowByIDParamsWithContext creates a new GetWorkflowByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkflowByIDParamsWithContext(ctx context.Context) *GetWorkflowByIDParams {
	var ()
	return &GetWorkflowByIDParams{

		Context: ctx,
	}
}

// NewGetWorkflowByIDParamsWithHTTPClient creates a new GetWorkflowByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkflowByIDParamsWithHTTPClient(client *http.Client) *GetWorkflowByIDParams {
	var ()
	return &GetWorkflowByIDParams{
		HTTPClient: client,
	}
}

/*GetWorkflowByIDParams contains all the parameters to send to the API endpoint
for the get workflow by Id operation typically these are written to a http.Request
*/
type GetWorkflowByIDParams struct {

	/*ID
	  id

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get workflow by Id params
func (o *GetWorkflowByIDParams) WithTimeout(timeout time.Duration) *GetWorkflowByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workflow by Id params
func (o *GetWorkflowByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workflow by Id params
func (o *GetWorkflowByIDParams) WithContext(ctx context.Context) *GetWorkflowByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workflow by Id params
func (o *GetWorkflowByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workflow by Id params
func (o *GetWorkflowByIDParams) WithHTTPClient(client *http.Client) *GetWorkflowByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workflow by Id params
func (o *GetWorkflowByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get workflow by Id params
func (o *GetWorkflowByIDParams) WithID(id string) *GetWorkflowByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get workflow by Id params
func (o *GetWorkflowByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
