// Code generated by go-swagger; DO NOT EDIT.

package command_runner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllKeywordsOfCLIsAcceptedByCommandRunnerParams creates a new GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams object
// with the default values initialized.
func NewGetAllKeywordsOfCLIsAcceptedByCommandRunnerParams() *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams {

	return &GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllKeywordsOfCLIsAcceptedByCommandRunnerParamsWithTimeout creates a new GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllKeywordsOfCLIsAcceptedByCommandRunnerParamsWithTimeout(timeout time.Duration) *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams {

	return &GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams{

		timeout: timeout,
	}
}

// NewGetAllKeywordsOfCLIsAcceptedByCommandRunnerParamsWithContext creates a new GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllKeywordsOfCLIsAcceptedByCommandRunnerParamsWithContext(ctx context.Context) *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams {

	return &GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams{

		Context: ctx,
	}
}

// NewGetAllKeywordsOfCLIsAcceptedByCommandRunnerParamsWithHTTPClient creates a new GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllKeywordsOfCLIsAcceptedByCommandRunnerParamsWithHTTPClient(client *http.Client) *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams {

	return &GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams{
		HTTPClient: client,
	}
}

/*GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams contains all the parameters to send to the API endpoint
for the get all keywords of c l is accepted by command runner operation typically these are written to a http.Request
*/
type GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all keywords of c l is accepted by command runner params
func (o *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams) WithTimeout(timeout time.Duration) *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all keywords of c l is accepted by command runner params
func (o *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all keywords of c l is accepted by command runner params
func (o *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams) WithContext(ctx context.Context) *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all keywords of c l is accepted by command runner params
func (o *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all keywords of c l is accepted by command runner params
func (o *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams) WithHTTPClient(client *http.Client) *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all keywords of c l is accepted by command runner params
func (o *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllKeywordsOfCLIsAcceptedByCommandRunnerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
