// Code generated by go-swagger; DO NOT EDIT.

package network_discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kszafran/junction-2018/models"
)

// NewCreateHTTPReadCredentialsParams creates a new CreateHTTPReadCredentialsParams object
// with the default values initialized.
func NewCreateHTTPReadCredentialsParams() *CreateHTTPReadCredentialsParams {
	var (
		contentTypeDefault = string("application/json")
	)
	return &CreateHTTPReadCredentialsParams{
		ContentType: contentTypeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateHTTPReadCredentialsParamsWithTimeout creates a new CreateHTTPReadCredentialsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateHTTPReadCredentialsParamsWithTimeout(timeout time.Duration) *CreateHTTPReadCredentialsParams {
	var (
		contentTypeDefault = string("application/json")
	)
	return &CreateHTTPReadCredentialsParams{
		ContentType: contentTypeDefault,

		timeout: timeout,
	}
}

// NewCreateHTTPReadCredentialsParamsWithContext creates a new CreateHTTPReadCredentialsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateHTTPReadCredentialsParamsWithContext(ctx context.Context) *CreateHTTPReadCredentialsParams {
	var (
		contentTypeDefault = string("application/json")
	)
	return &CreateHTTPReadCredentialsParams{
		ContentType: contentTypeDefault,

		Context: ctx,
	}
}

// NewCreateHTTPReadCredentialsParamsWithHTTPClient creates a new CreateHTTPReadCredentialsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateHTTPReadCredentialsParamsWithHTTPClient(client *http.Client) *CreateHTTPReadCredentialsParams {
	var (
		contentTypeDefault = string("application/json")
	)
	return &CreateHTTPReadCredentialsParams{
		ContentType: contentTypeDefault,
		HTTPClient:  client,
	}
}

/*CreateHTTPReadCredentialsParams contains all the parameters to send to the API endpoint
for the create HTTP read credentials operation typically these are written to a http.Request
*/
type CreateHTTPReadCredentialsParams struct {

	/*ContentType
	  Request body content type

	*/
	ContentType string
	/*Request
	  request

	*/
	Request models.HTTPReadCredentialDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create HTTP read credentials params
func (o *CreateHTTPReadCredentialsParams) WithTimeout(timeout time.Duration) *CreateHTTPReadCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create HTTP read credentials params
func (o *CreateHTTPReadCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create HTTP read credentials params
func (o *CreateHTTPReadCredentialsParams) WithContext(ctx context.Context) *CreateHTTPReadCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create HTTP read credentials params
func (o *CreateHTTPReadCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create HTTP read credentials params
func (o *CreateHTTPReadCredentialsParams) WithHTTPClient(client *http.Client) *CreateHTTPReadCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create HTTP read credentials params
func (o *CreateHTTPReadCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the create HTTP read credentials params
func (o *CreateHTTPReadCredentialsParams) WithContentType(contentType string) *CreateHTTPReadCredentialsParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the create HTTP read credentials params
func (o *CreateHTTPReadCredentialsParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithRequest adds the request to the create HTTP read credentials params
func (o *CreateHTTPReadCredentialsParams) WithRequest(request models.HTTPReadCredentialDTO) *CreateHTTPReadCredentialsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create HTTP read credentials params
func (o *CreateHTTPReadCredentialsParams) SetRequest(request models.HTTPReadCredentialDTO) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateHTTPReadCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
