// Code generated by go-swagger; DO NOT EDIT.

package network_discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kszafran/junction-2018/models"
)

// NewCreateUpdateSNMPPropertiesParams creates a new CreateUpdateSNMPPropertiesParams object
// with the default values initialized.
func NewCreateUpdateSNMPPropertiesParams() *CreateUpdateSNMPPropertiesParams {
	var (
		contentTypeDefault = string("application/json")
	)
	return &CreateUpdateSNMPPropertiesParams{
		ContentType: contentTypeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateUpdateSNMPPropertiesParamsWithTimeout creates a new CreateUpdateSNMPPropertiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateUpdateSNMPPropertiesParamsWithTimeout(timeout time.Duration) *CreateUpdateSNMPPropertiesParams {
	var (
		contentTypeDefault = string("application/json")
	)
	return &CreateUpdateSNMPPropertiesParams{
		ContentType: contentTypeDefault,

		timeout: timeout,
	}
}

// NewCreateUpdateSNMPPropertiesParamsWithContext creates a new CreateUpdateSNMPPropertiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateUpdateSNMPPropertiesParamsWithContext(ctx context.Context) *CreateUpdateSNMPPropertiesParams {
	var (
		contentTypeDefault = string("application/json")
	)
	return &CreateUpdateSNMPPropertiesParams{
		ContentType: contentTypeDefault,

		Context: ctx,
	}
}

// NewCreateUpdateSNMPPropertiesParamsWithHTTPClient creates a new CreateUpdateSNMPPropertiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateUpdateSNMPPropertiesParamsWithHTTPClient(client *http.Client) *CreateUpdateSNMPPropertiesParams {
	var (
		contentTypeDefault = string("application/json")
	)
	return &CreateUpdateSNMPPropertiesParams{
		ContentType: contentTypeDefault,
		HTTPClient:  client,
	}
}

/*CreateUpdateSNMPPropertiesParams contains all the parameters to send to the API endpoint
for the create update s n m p properties operation typically these are written to a http.Request
*/
type CreateUpdateSNMPPropertiesParams struct {

	/*ContentType
	  Request body content type

	*/
	ContentType string
	/*Request
	  request

	*/
	Request models.SystemPropertyNameAndIntValueDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create update s n m p properties params
func (o *CreateUpdateSNMPPropertiesParams) WithTimeout(timeout time.Duration) *CreateUpdateSNMPPropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create update s n m p properties params
func (o *CreateUpdateSNMPPropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create update s n m p properties params
func (o *CreateUpdateSNMPPropertiesParams) WithContext(ctx context.Context) *CreateUpdateSNMPPropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create update s n m p properties params
func (o *CreateUpdateSNMPPropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create update s n m p properties params
func (o *CreateUpdateSNMPPropertiesParams) WithHTTPClient(client *http.Client) *CreateUpdateSNMPPropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create update s n m p properties params
func (o *CreateUpdateSNMPPropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the create update s n m p properties params
func (o *CreateUpdateSNMPPropertiesParams) WithContentType(contentType string) *CreateUpdateSNMPPropertiesParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the create update s n m p properties params
func (o *CreateUpdateSNMPPropertiesParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithRequest adds the request to the create update s n m p properties params
func (o *CreateUpdateSNMPPropertiesParams) WithRequest(request models.SystemPropertyNameAndIntValueDTO) *CreateUpdateSNMPPropertiesParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create update s n m p properties params
func (o *CreateUpdateSNMPPropertiesParams) SetRequest(request models.SystemPropertyNameAndIntValueDTO) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateUpdateSNMPPropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
