// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClaimDeviceRequest claim device request
// swagger:model ClaimDeviceRequest
type ClaimDeviceRequest struct {

	// config file Url
	ConfigFileURL string `json:"configFileUrl,omitempty"`

	// config Id
	ConfigID string `json:"configId,omitempty"`

	// device claim list
	DeviceClaimList []*ClaimDeviceRequestDeviceClaimListItems0 `json:"deviceClaimList"`

	// file service Id
	FileServiceID string `json:"fileServiceId,omitempty"`

	// image Id
	ImageID string `json:"imageId,omitempty"`

	// image Url
	ImageURL string `json:"imageUrl,omitempty"`

	// populate inventory
	PopulateInventory bool `json:"populateInventory,omitempty"`

	// project Id
	ProjectID string `json:"projectId,omitempty"`

	// workflow Id
	WorkflowID string `json:"workflowId,omitempty"`
}

// Validate validates this claim device request
func (m *ClaimDeviceRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceClaimList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClaimDeviceRequest) validateDeviceClaimList(formats strfmt.Registry) error {

	if swag.IsZero(m.DeviceClaimList) { // not required
		return nil
	}

	for i := 0; i < len(m.DeviceClaimList); i++ {
		if swag.IsZero(m.DeviceClaimList[i]) { // not required
			continue
		}

		if m.DeviceClaimList[i] != nil {
			if err := m.DeviceClaimList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deviceClaimList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClaimDeviceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClaimDeviceRequest) UnmarshalBinary(b []byte) error {
	var res ClaimDeviceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ClaimDeviceRequestDeviceClaimListItems0 claim device request device claim list items0
// swagger:model ClaimDeviceRequestDeviceClaimListItems0
type ClaimDeviceRequestDeviceClaimListItems0 struct {

	// config list
	ConfigList []*ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0 `json:"configList"`

	// device Id
	DeviceID string `json:"deviceId,omitempty"`

	// license level
	LicenseLevel string `json:"licenseLevel,omitempty"`

	// license type
	LicenseType string `json:"licenseType,omitempty"`

	// top of stack serial number
	TopOfStackSerialNumber string `json:"topOfStackSerialNumber,omitempty"`
}

// Validate validates this claim device request device claim list items0
func (m *ClaimDeviceRequestDeviceClaimListItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfigList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClaimDeviceRequestDeviceClaimListItems0) validateConfigList(formats strfmt.Registry) error {

	if swag.IsZero(m.ConfigList) { // not required
		return nil
	}

	for i := 0; i < len(m.ConfigList); i++ {
		if swag.IsZero(m.ConfigList[i]) { // not required
			continue
		}

		if m.ConfigList[i] != nil {
			if err := m.ConfigList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("configList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClaimDeviceRequestDeviceClaimListItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClaimDeviceRequestDeviceClaimListItems0) UnmarshalBinary(b []byte) error {
	var res ClaimDeviceRequestDeviceClaimListItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0 claim device request device claim list items0 config list items0
// swagger:model ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0
type ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0 struct {

	// config Id
	ConfigID string `json:"configId,omitempty"`

	// config parameters
	ConfigParameters []*ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0ConfigParametersItems0 `json:"configParameters"`
}

// Validate validates this claim device request device claim list items0 config list items0
func (m *ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfigParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0) validateConfigParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.ConfigParameters) { // not required
		return nil
	}

	for i := 0; i < len(m.ConfigParameters); i++ {
		if swag.IsZero(m.ConfigParameters[i]) { // not required
			continue
		}

		if m.ConfigParameters[i] != nil {
			if err := m.ConfigParameters[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("configParameters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0) UnmarshalBinary(b []byte) error {
	var res ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0ConfigParametersItems0 claim device request device claim list items0 config list items0 config parameters items0
// swagger:model ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0ConfigParametersItems0
type ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0ConfigParametersItems0 struct {

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this claim device request device claim list items0 config list items0 config parameters items0
func (m *ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0ConfigParametersItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0ConfigParametersItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0ConfigParametersItems0) UnmarshalBinary(b []byte) error {
	var res ClaimDeviceRequestDeviceClaimListItems0ConfigListItems0ConfigParametersItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
