// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CreateSiteResponse create site response
// swagger:model CreateSiteResponse
type CreateSiteResponse struct {

	// execution Id
	ExecutionID string `json:"executionId,omitempty"`

	// execution status Url
	ExecutionStatusURL string `json:"executionStatusUrl,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this create site response
func (m *CreateSiteResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSiteResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSiteResponse) UnmarshalBinary(b []byte) error {
	var res CreateSiteResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
