// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetWorkflowCountResponse get workflow count response
// swagger:model GetWorkflowCountResponse
type GetWorkflowCountResponse struct {

	// response
	Response float64 `json:"response,omitempty"`
}

// Validate validates this get workflow count response
func (m *GetWorkflowCountResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetWorkflowCountResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetWorkflowCountResponse) UnmarshalBinary(b []byte) error {
	var res GetWorkflowCountResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
